version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: tlynTask-app
    restart: unless-stopped
    ports:
      - "8082:80"  
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      - PHP_IDE_CONFIG="serverName=local"
    networks:
      - tlynTask-network

  db:
    image: mysql:8.0
    container_name: tlynTask-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tlyn_task
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - tlynTask-db-data:/var/lib/mysql
    networks:
      - tlynTask-network

networks:
  tlynTask-network:
    driver: bridge

volumes:
  tlynTask-db-data:
    driver: local
